version: '3'
services:
  graphql-geo:
    image: "graphql-geo:prod"
    build:
      context: ../../
      dockerfile: etc/docker/Dockerfile-prod
    depends_on:
      - postgis
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URL: "postgresql://postgres:password@postgis:5432/postgres"
      PYTHONPATH: /home/graphql-geo