FROM python:3.7.2-alpine3.8

COPY requirements.txt /tmp/requirements.txt

RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r /tmp/requirements.txt --no-cache-dir && \
 apk --purge del .build-deps

WORKDIR /home/graphql-geo

CMD bin/geo

