"""first revision

Revision ID: 9d2ad96dbda8
Revises: 
Create Date: 2019-01-25 18:17:30.799171

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9d2ad96dbda8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "center", geoalchemy2.types.Geography(geometry_type="POINT"), nullable=False
        ),
        sa.Column(
            "polygon",
            geoalchemy2.types.Geography(geometry_type="POLYGON"),
            nullable=False,
        ),
        sa.Column("popularity", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("place")
    # ### end Alembic commands ###
